version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-230303"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lj0hde2i8b64"
s3_prefix = "sam-app-230303"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
